name: CI Frontend

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm install

      - name: Build
        env:
          VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}
          VITE_DOMAIN_WEB: ${{ vars.VITE_DOMAIN_WEB }}
        run: npm run build